### ISSUE TITLE
 not compile em visual studio

### ISSUE THREAD

**Issue by marcelomelofreitas** [Unitrunker/Tile#1]
Estudei o codigo fonte do seu programa, ele é muito bem feito, parabens, aprendi muito com ele, porem ele nao compila em nenhuma das versoes atual do visual c++ express. Parabens pelo projeto, mas quero fazer uma pergunta, voce abandonou ele? tem anos que nao tem atualizacao, poderia me ajudar a compila-lo no visual studio 2017 ?

**Comment by Unitrunker** [comment]
Halo Marcello!

I do not have VS.2017. I will make a guess that you do not have WTL
installed. That will prevent the window implementation that uses WTL
(Windows Template Library) from compiling.

http://wtl.sourceforge.net/


​

**Comment by marcelomelofreitas** [comment]
Obrigado, funcionou! com o WTL realmente estava faltando
